version: 0.2

phases:
  install:
    commands:
      - cd eks
      - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      - mv kubectl /usr/local/bin/kubectl
      - chmod 0755 /usr/local/bin/kubectl
      - wget https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip
      - unzip terraform_1.6.6_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - terraform --version

  pre_build:
    commands:
      - terraform init

  build:
    commands:
      - kubectl get pods --kubeconfig ~/.kube/config
      - terraform plan -out=plan.out

artifacts:
  files:
    - eks/**/*