version: 0.2

phases:
  install:
    commands:
      - cd eks
      - wget https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip
      - unzip terraform_1.6.6_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - terraform --version
      
  pre_build:
    commands:
      - aws eks --region us-east-1 update-kubeconfig --name afsdemo || echo 0
      - terraform init

  build:
    commands:
      - terraform apply -input=false plan.out
  
  post_build:
    commands:
      - aws eks --region us-east-1 update-kubeconfig --name afsdemo